"""Curated symbol universes: ~190 stocks and ~90 cryptocurrencies.

(ticker, name, approx price USD). Prices only seed the deterministic
simulator — live feeds override them when a data provider supports the symbol.
Anything not listed can still be added as a custom ticker in the app.
"""

STOCKS: list[tuple[str, str, float]] = [
    # Мега-кэп технологии
    ("AAPL", "Apple", 210), ("MSFT", "Microsoft", 450), ("GOOGL", "Alphabet A", 180),
    ("GOOG", "Alphabet C", 182), ("AMZN", "Amazon", 185), ("NVDA", "NVIDIA", 125),
    ("META", "Meta Platforms", 500), ("TSLA", "Tesla", 250), ("AVGO", "Broadcom", 170),
    ("ORCL", "Oracle", 140), ("CRM", "Salesforce", 260), ("ADBE", "Adobe", 520),
    ("AMD", "AMD", 160), ("INTC", "Intel", 32), ("QCOM", "Qualcomm", 200),
    ("TXN", "Texas Instruments", 195), ("MU", "Micron", 130), ("AMAT", "Applied Materials", 230),
    ("ASML", "ASML", 1000), ("TSM", "TSMC", 170), ("LRCX", "Lam Research", 1000),
    ("KLAC", "KLA", 820), ("SNPS", "Synopsys", 580), ("CDNS", "Cadence", 300),
    ("NOW", "ServiceNow", 780), ("INTU", "Intuit", 640), ("IBM", "IBM", 175),
    ("CSCO", "Cisco", 47), ("ACN", "Accenture", 320), ("SAP", "SAP", 190),
    ("SHOP", "Shopify", 65), ("SQ", "Block", 65), ("PYPL", "PayPal", 62),
    ("UBER", "Uber", 70), ("LYFT", "Lyft", 15), ("ABNB", "Airbnb", 150),
    ("SNOW", "Snowflake", 130), ("PLTR", "Palantir", 25), ("NET", "Cloudflare", 80),
    ("DDOG", "Datadog", 120), ("MDB", "MongoDB", 250), ("CRWD", "CrowdStrike", 300),
    ("ZS", "Zscaler", 180), ("PANW", "Palo Alto Networks", 300), ("FTNT", "Fortinet", 60),
    ("OKTA", "Okta", 90), ("TEAM", "Atlassian", 170), ("WDAY", "Workday", 230),
    ("ADSK", "Autodesk", 240), ("ANSS", "Ansys", 320), ("ROP", "Roper", 550),
    ("SMCI", "Super Micro", 800), ("ARM", "Arm Holdings", 130), ("DELL", "Dell", 140),
    ("HPQ", "HP", 35), ("HPE", "HPE", 20), ("STX", "Seagate", 100), ("WDC", "Western Digital", 70),
    ("SONY", "Sony", 85), ("BABA", "Alibaba", 75), ("JD", "JD.com", 28),
    ("PDD", "PDD Holdings", 140), ("BIDU", "Baidu", 90), ("NTES", "NetEase", 95),
    ("SE", "Sea Limited", 70), ("MELI", "MercadoLibre", 1650), ("SPOT", "Spotify", 310),
    ("NFLX", "Netflix", 650), ("DIS", "Disney", 100), ("RBLX", "Roblox", 38),
    ("EA", "Electronic Arts", 140), ("TTWO", "Take-Two", 155), ("U", "Unity", 22),
    ("COIN", "Coinbase", 220), ("HOOD", "Robinhood", 20), ("MSTR", "MicroStrategy", 1500),
    # Финансы
    ("JPM", "JPMorgan Chase", 200), ("BAC", "Bank of America", 40), ("WFC", "Wells Fargo", 60),
    ("C", "Citigroup", 62), ("GS", "Goldman Sachs", 460), ("MS", "Morgan Stanley", 98),
    ("SCHW", "Charles Schwab", 73), ("BLK", "BlackRock", 800), ("BX", "Blackstone", 125),
    ("KKR", "KKR", 105), ("V", "Visa", 270), ("MA", "Mastercard", 450),
    ("AXP", "American Express", 230), ("COF", "Capital One", 140), ("USB", "US Bancorp", 42),
    ("PNC", "PNC", 155), ("TFC", "Truist", 40), ("BK", "BNY Mellon", 58),
    ("BRK.B", "Berkshire Hathaway B", 410), ("PGR", "Progressive", 210), ("ALL", "Allstate", 165),
    ("MET", "MetLife", 72), ("AIG", "AIG", 75), ("CB", "Chubb", 260),
    # Здравоохранение
    ("UNH", "UnitedHealth", 500), ("JNJ", "Johnson & Johnson", 150), ("LLY", "Eli Lilly", 880),
    ("PFE", "Pfizer", 28), ("MRK", "Merck", 128), ("ABBV", "AbbVie", 165),
    ("TMO", "Thermo Fisher", 550), ("ABT", "Abbott", 105), ("DHR", "Danaher", 250),
    ("BMY", "Bristol Myers", 42), ("AMGN", "Amgen", 310), ("GILD", "Gilead", 68),
    ("VRTX", "Vertex", 460), ("REGN", "Regeneron", 1050), ("MRNA", "Moderna", 120),
    ("BIIB", "Biogen", 220), ("ISRG", "Intuitive Surgical", 430), ("SYK", "Stryker", 340),
    ("BSX", "Boston Scientific", 75), ("MDT", "Medtronic", 82), ("CI", "Cigna", 340),
    ("CVS", "CVS Health", 60), ("HUM", "Humana", 360), ("ZTS", "Zoetis", 175),
    # Потребительский сектор
    ("WMT", "Walmart", 68), ("COST", "Costco", 850), ("TGT", "Target", 145),
    ("HD", "Home Depot", 340), ("LOW", "Lowe's", 230), ("MCD", "McDonald's", 260),
    ("SBUX", "Starbucks", 78), ("CMG", "Chipotle", 62), ("YUM", "Yum! Brands", 135),
    ("NKE", "Nike", 76), ("LULU", "Lululemon", 290), ("TJX", "TJX", 110),
    ("PG", "Procter & Gamble", 165), ("KO", "Coca-Cola", 62), ("PEP", "PepsiCo", 170),
    ("PM", "Philip Morris", 105), ("MO", "Altria", 45), ("MDLZ", "Mondelez", 68),
    ("CL", "Colgate-Palmolive", 92), ("KMB", "Kimberly-Clark", 135), ("EL", "Estee Lauder", 105),
    ("GM", "General Motors", 46), ("F", "Ford", 11), ("RIVN", "Rivian", 12),
    ("LCID", "Lucid", 3), ("NIO", "NIO", 5), ("LI", "Li Auto", 20), ("XPEV", "XPeng", 8),
    ("TM", "Toyota", 200), ("MAR", "Marriott", 240), ("HLT", "Hilton", 210),
    ("BKNG", "Booking", 3800), ("EXPE", "Expedia", 130), ("DAL", "Delta", 48),
    ("UAL", "United Airlines", 50), ("AAL", "American Airlines", 11), ("LUV", "Southwest", 28),
    ("CCL", "Carnival", 17), ("RCL", "Royal Caribbean", 155), ("DKNG", "DraftKings", 38),
    # Промышленность и энергетика
    ("CAT", "Caterpillar", 340), ("DE", "Deere", 380), ("BA", "Boeing", 180),
    ("LMT", "Lockheed Martin", 470), ("RTX", "RTX", 105), ("NOC", "Northrop Grumman", 480),
    ("GD", "General Dynamics", 290), ("GE", "GE Aerospace", 160), ("HON", "Honeywell", 210),
    ("MMM", "3M", 100), ("UPS", "UPS", 135), ("FDX", "FedEx", 260),
    ("UNP", "Union Pacific", 240), ("CSX", "CSX", 34), ("ETN", "Eaton", 320),
    ("EMR", "Emerson", 110), ("ITW", "Illinois Tool Works", 245), ("PH", "Parker Hannifin", 540),
    ("XOM", "Exxon Mobil", 115), ("CVX", "Chevron", 155), ("COP", "ConocoPhillips", 110),
    ("SLB", "Schlumberger", 45), ("EOG", "EOG Resources", 125), ("OXY", "Occidental", 60),
    ("PSX", "Phillips 66", 140), ("VLO", "Valero", 155), ("MPC", "Marathon Petroleum", 175),
    ("NEE", "NextEra Energy", 72), ("DUK", "Duke Energy", 105), ("SO", "Southern Company", 80),
    # Связь и прочее
    ("T", "AT&T", 18), ("VZ", "Verizon", 41), ("TMUS", "T-Mobile", 180),
    ("CMCSA", "Comcast", 38), ("CHTR", "Charter", 300), ("LIN", "Linde", 440),
    ("APD", "Air Products", 260), ("SHW", "Sherwin-Williams", 310), ("FCX", "Freeport-McMoRan", 48),
    ("NEM", "Newmont", 45), ("NUE", "Nucor", 165), ("AA", "Alcoa", 38),
]

CRYPTO: list[tuple[str, str, float]] = [
    ("BTC", "Bitcoin", 65000), ("ETH", "Ethereum", 3500), ("SOL", "Solana", 150),
    ("BNB", "BNB", 600), ("XRP", "XRP", 0.60), ("ADA", "Cardano", 0.45),
    ("DOGE", "Dogecoin", 0.15), ("AVAX", "Avalanche", 30), ("DOT", "Polkadot", 6),
    ("LINK", "Chainlink", 15), ("TON", "Toncoin", 7), ("TRX", "TRON", 0.12),
    ("POL", "Polygon", 0.5), ("SHIB", "Shiba Inu", 0.000022), ("LTC", "Litecoin", 80),
    ("BCH", "Bitcoin Cash", 450), ("UNI", "Uniswap", 8), ("ATOM", "Cosmos", 8),
    ("XLM", "Stellar", 0.11), ("NEAR", "NEAR Protocol", 5.5), ("APT", "Aptos", 8),
    ("ARB", "Arbitrum", 0.8), ("OP", "Optimism", 1.8), ("SUI", "Sui", 1.0),
    ("PEPE", "Pepe", 0.000011), ("WIF", "dogwifhat", 2), ("INJ", "Injective", 22),
    ("FIL", "Filecoin", 5), ("IMX", "Immutable", 1.5), ("HBAR", "Hedera", 0.08),
    ("VET", "VeChain", 0.03), ("RNDR", "Render", 7), ("GRT", "The Graph", 0.2),
    ("AAVE", "Aave", 90), ("MKR", "Maker", 2400), ("ALGO", "Algorand", 0.18),
    ("FTM", "Fantom", 0.7), ("SAND", "The Sandbox", 0.4), ("MANA", "Decentraland", 0.4),
    ("AXS", "Axie Infinity", 6), ("THETA", "Theta", 1.5), ("EGLD", "MultiversX", 35),
    ("XTZ", "Tezos", 0.9), ("EOS", "EOS", 0.6), ("FLOW", "Flow", 0.6),
    ("CHZ", "Chiliz", 0.08), ("CRV", "Curve", 0.4), ("LDO", "Lido DAO", 2),
    ("SNX", "Synthetix", 2.5), ("COMP", "Compound", 55), ("ENS", "ENS", 25),
    ("DYDX", "dYdX", 1.5), ("GMX", "GMX", 30), ("KAS", "Kaspa", 0.15),
    ("SEI", "Sei", 0.4), ("TIA", "Celestia", 6), ("JUP", "Jupiter", 0.8),
    ("PYTH", "Pyth Network", 0.4), ("ONDO", "Ondo", 1.2), ("ENA", "Ethena", 0.8),
    ("WLD", "Worldcoin", 2.5), ("STRK", "Starknet", 0.7), ("JTO", "Jito", 3),
    ("BONK", "Bonk", 0.00002), ("FLOKI", "Floki", 0.0002), ("NOT", "Notcoin", 0.01),
    ("TAO", "Bittensor", 350), ("ICP", "Internet Computer", 10), ("ETC", "Ethereum Classic", 25),
    ("XMR", "Monero", 160), ("ZEC", "Zcash", 30), ("DASH", "Dash", 30),
    ("NEO", "NEO", 12), ("IOTA", "IOTA", 0.2), ("QNT", "Quant", 90),
    ("RUNE", "THORChain", 4), ("KAVA", "Kava", 0.7), ("ROSE", "Oasis", 0.08),
    ("ONE", "Harmony", 0.02), ("GALA", "Gala", 0.03), ("ENJ", "Enjin", 0.3),
    ("BAT", "Basic Attention", 0.25), ("ZIL", "Zilliqa", 0.02), ("CAKE", "PancakeSwap", 2.5),
    ("MINA", "Mina", 0.6), ("AR", "Arweave", 30),
    ("OCEAN", "Ocean Protocol", 0.6), ("FET", "Fetch.ai", 1.5), ("AGIX", "SingularityNET", 0.6),
]
